# Generated by Django 4.2.7 on 2023-12-06 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_alter_warnings_got_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warnings',
            name='got_at',
        ),
        migrations.AddField(
            model_name='warnings',
            name='warnings_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blocks',
            name='blocked_until',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 16, 13, 21, 46, 650285, tzinfo=datetime.timezone.utc), verbose_name='Blocked until'),
        ),
    ]
