# Generated by Django 4.2.7 on 2023-12-06 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_remove_warnings_got_at_warnings_warnings_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocks',
            name='blocked_until',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 16, 13, 33, 24, 519797, tzinfo=datetime.timezone.utc), verbose_name='Blocked until'),
        ),
        migrations.AlterField(
            model_name='warnings',
            name='bad_words_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='warnings',
            name='warnings_count',
            field=models.IntegerField(default=0),
        ),
    ]
