# Generated by Django 4.2.7 on 2023-12-06 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_alter_blocks_blocked_until_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocks',
            name='blocked_until',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 16, 13, 35, 45, 370842, tzinfo=datetime.timezone.utc), verbose_name='Blocked until'),
        ),
    ]
