# Generated by Django 4.2.7 on 2023-12-14 09:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0013_alter_blocks_blocked_until_like_dislike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocks',
            name='blocked_until',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 24, 9, 46, 43, 374733, tzinfo=datetime.timezone.utc), verbose_name='Blocked until'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber', to=settings.AUTH_USER_MODEL)),
                ('user_to_subscribe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_to_subscribe', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
