# Generated by Django 4.2.7 on 2023-12-19 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0016_alter_blocks_blocked_until_userbadgestracker_badges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocks',
            name='blocked_until',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 29, 12, 24, 21, 412362, tzinfo=datetime.timezone.utc), verbose_name='Blocked until'),
        ),
    ]
