# Generated by Django 4.2.7 on 2023-12-19 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0017_alter_blocks_blocked_until'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbadgestracker',
            name='user',
        ),
        migrations.AlterField(
            model_name='blocks',
            name='blocked_until',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 29, 12, 27, 4, 102193, tzinfo=datetime.timezone.utc), verbose_name='Blocked until'),
        ),
        migrations.DeleteModel(
            name='Badges',
        ),
        migrations.DeleteModel(
            name='UserBadgesTracker',
        ),
    ]
