# Generated by Django 4.2.7 on 2023-12-21 13:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0020_alter_badges_user_alter_blocks_blocked_until'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badges',
            old_name='badge',
            new_name='description',
        ),
        migrations.AddField(
            model_name='badges',
            name='type',
            field=models.CharField(choices=[('post', 'Post'), ('likes_did', 'Likes did'), ('likes_recieved', 'Likes recieved'), ('login_streak', 'Login streaks')], default='post', max_length=25),
        ),
        migrations.AlterField(
            model_name='blocks',
            name='blocked_until',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 31, 13, 50, 31, 691097, tzinfo=datetime.timezone.utc), verbose_name='Blocked until'),
        ),
        migrations.CreateModel(
            name='LoginStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now)),
                ('streak_count', models.PositiveIntegerField(default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
