# Generated by Django 4.2.7 on 2023-12-26 09:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0021_rename_badge_badges_description_badges_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocks',
            name='blocked_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Blocked at'),
        ),
        migrations.AlterField(
            model_name='blocks',
            name='blocked_until',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 5, 9, 50, 50, 145712, tzinfo=datetime.timezone.utc), verbose_name='Blocked until'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='loginstreak',
            name='last_login',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='postsread',
            name='read_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Read at'),
        ),
        migrations.AlterField(
            model_name='warnings',
            name='bad_words_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='warnings',
            name='warnings_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
